This test was aborted because of a previous failure (see below).

You're calling `iseven` every time.
